travis:
  secure:
    BINSTAR_TOKEN: Ei1zbkJNGrWD9jpIDVYopVjexPKSMeidiVvt218o72ZeYDIErNHR0ny+kth4cNMXdvj3ponlsaErYlnOe43DqK9Ead4yIRFOPl6qrlCdEiEMjokq8LMmrrl8h1IFBzY+wybHp0e5sFlBD902b7z9Qc2DOzUKeTt9YRQj5DkYuSnXfCOWCcLSAlyoZOlAeCMXj9Oottr6pxTIClOOolPigc8AdvLjZYTdaNSOdI2RLgYLKCM9SOf7jCuCZDbcHNV6lo1uO48hRMstKvUy0bGL/V20td1hPdYoOTqDQmOaeluymh//hL+07cCfc/qqMEHXJohzV0bQl0VjJfFXi3GKR3uS9TtP3zwZJ+6rB0DEuaMwafukz9pIk068BWAXgHOP9u9q7CzAzvs55JUqb8w5Xc6QikYkS950ANpxEkSdC8oUqTMLx7xV83C6vCF+OuIDy+tzp7ems0xmkwp0JhFlXBxyxavn5O2rEl7AmncK3ufOPny+EtbQ4Nkcg/yQVERhZW0tFF+SORnqMMT7mYYqfk55tLN0AMa1fsUoLguK+llxcUQtu7tqu0FEHL02SBNJCWLehea1H1DvetTs4xSGtqVZds9flVU7XqFCgHHtP0p4N68/hIp5nvZLuWbabFyUGVJ5lZbWRNflPNTLCACUOWhhbuRTLX8HvM1ea2o4jLU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
